version: "2.1"
services:
  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - WEBUI_PORT=8080
    volumes:
      - ./config/config:/config
      - ~/Downloads/:/downloads
      - ~/QBWeb/vuetorrent/:/home/
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    restart: always