version: "2.1"
services:
  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
# for 8090 set -p 8090:8090  WEBUI_PORT=8090
      - WEBUI_PORT=8888
    volumes:
      - ./config/config:/config
      # - ~/Downloads/:/downloads
      # - ~/QBWeb/vuetorrent/:/home/
    ports:
      - 6881:6881
      - 6881:6881/udp
      # - 8888:8888
    expose:
      - 8888
    restart: always
    networks:
      - traefik

networks:
  traefik:
    name: traefik
    external: true
