version: '3.8'

services:
  mcjava:
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      VERSION: 1.18.1
      DIFFICULTY: normal
      # TYPE: PAPER
    ports:
      - 25565:25565
    volumes:
      - ./mcdata/:/data

