name: filebrowser
services:
  filebrowser:
    image: hurlenko/filebrowser
    volumes:
      # - /mnt/f:/data
      - ./data/config/:/config
    environment:
      - FB_BASEURL=/filebrowser
    # env_file: .env
    ports:
      - '8024:8080'
    restart: always
    user: "${UID}:${GID}"

networks:
  traefik:
    name: traefik
    driver: bridge
    external: true
