name: authelia
services:
  authelia:
    image: 'authelia/authelia:latest'
    container_name: 'authelia'
    volumes:
      - ./config:/config
      - ./secrets:/secrets:ro
      - ./logs:/var/log/authelia/
    environment:
      TZ: 'America/Los_Angeles'
      X_AUTHELIA_CONFIG_FILTERS: 'template'
    networks:
      - traefik
    restart: 'unless-stopped'

networks:
  traefik:
    external: true
    name: traefik
