global:
  checkNewVersion: true
  sendAnonymousUsage: false

log:
 level: DEBUG  # DEBUG, INFO, WARNING, ERROR, CRITICAL

api:
 dashboard: true  # true by default
 insecure: false  # Don't do this in production!

# Entry Points configuration
# ---
entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443



certificatesResolvers:
  # myresolver:
  #   acme:
  #     email: devozakione@gmail.com
  #     storage: /letsencrypt/acme.json
  #     caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
  #     tlsChallenge: {}

  production:
    acme:
      email: devozakione@gmail.com
      storage: /letsencrypt/acme.json
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      # tlsChallenge: {}
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 10
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"

providers:
  docker:
    exposedByDefault: false  # Default is true
    watch: true
  file:
    # watch for dynamic configuration changes
    directory: /etc/traefik/hotreload
    watch: true
