global:
  checkNewVersion: true
  sendAnonymousUsage: false

log:
  level: DEBUG # DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "common"
  maxSize: 100
  maxBackups: 3
  maxAge: 3
  compress: true

api:
  dashboard: true
  insecure: false # Don't do this in production!

# Entry Points configuration
# ---
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
    transport:
      respondingTimeouts:
        readTimeout: "30m"
    http3:
      advertisedPort: 443
    http:
      tls:
        certResolver: "letsencrypt"
      encodedCharacters:
        allowEncodedSlash: true
        allowEncodedQuestionMark: true

experimental:
  plugins:
    badger:
      moduleName: "github.com/fosrl/badger"
      version: "v1.4.1"

certificatesResolvers:
  # myresolver:
  #   acme:
  #     email: devozakione@gmail.com
  #     storage: /letsencrypt/acme.json
  #     caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
  #     tlsChallenge: {}

  production:
    acme:
      email: devozakione@gmail.com
      storage: /letsencrypt/acme.json
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      # tlsChallenge: {}
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: "10"
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"

providers:
  docker:
    exposedByDefault: false # Default is true
    watch: true
  file:
    # watch for dynamic configuration changes
    directory: /etc/traefik/hotreload
    watch: true
  http:
    endpoint: "http://pangolin:3001/api/v1/traefik-config"
    pollInterval: "5s"
