name: emby
services:
  emby:
    image: emby/embyserver:4.5.0.13

    volumes:
      - ./config:/config
      - /mnt/f:/mnt/F
      - /mnt/g:/mnt/G
    env_file: .env
    ports:
      - '8096:8096' # To expose the HTTP port
      - '8920:8920' # To expose the HTTPS port
