up:
	docker-compose -f docker-compose.yml run --service-ports -d emby
# 	--service-ports binding sur la stack de ton ethernet oclahsot et 0.0.0.0.0
down:
	docker-compose -f docker-compose.yml down -v
# 	docker-compose down
# 	down -v
#	run => create container with given hash
#	stop hash
#	up hash
#	stop hash