version: "3.9"

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    env_file: .env
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./config/traefik/traefik.yml:/traefik.yml:ro"
      - "./config/hotreload/:/etc/traefik/hotreload"
    networks:
      - traefik

networks:
  traefik:
    name: traefik
    external: true
