name: traefik
services:
  traefik:
    image: traefik:v2.11
    container_name: traefik
    volumes:
      - ./letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik/traefik.yml:/traefik.yml:ro
      - ./config/hotreload/:/etc/traefik/hotreload
    env_file: .env
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    networks:
      - traefik

networks:
  traefik:
    name: traefik
    external: true
