[global]
  sendAnonymousUsage = false

[log]
  level = "DEBUG"
  format = "common"
## Static configuration
[entryPoints]
# basic
  [entryPoints.web]
    address = ":80"
  [entryPoints.websecure]
    address = ":443"

[providers]
  [providers.file]
    directory = "/etc/traefik/hotreload"
    watch = true

[api]
  dashboard = true
  #entryPoint = "dashboard"
  insecure = true
  debug = true

[certificatesResolvers.myresolver.acme]
  email = "trashozaki@gmail.com"
  caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
  storage = "/etc/traefik/hotreload/acme/acme.json"
  [certificatesResolvers.myresolver.acme.dnsChallenge]
    provider = "linode"
    delayBeforeCheck = 0
    resolvers = ["1.1.1.1:53","8.8.8.8:53"]
