[http]
############
# frontend #
############
[http.routers]
  [http.routers.frontend_torrent]
    rule = "PathPrefix(`/torrent`)"
    entryPoints = ["web"]
    middlewares = ["torrent-stripprefix"]
    service = "backend_torrent"
  
  [http.routers.frontend_filebrowser]
    rule = "Host(`172-104-239-86.ip.linodeusercontent.com`) && PathPrefix(`/filebrowser`)"
    entryPoints = ["websecure"]
    middlewares = ["filebrowser-stripprefix"]
    service = "backend_filebrowser"
    [http.routers.frontend_filebrowser.tls]
      certResolver = "myresolver"
      [http.routers.frontend_filebrowser.tls.domains]
        main = "172-104-239-86.ip.linodeusercontent.com"
        #sans = ["*.172-104-239-86.ip.linodeusercontent.com"]

###########
# backend #
###########
[http.services]
  [http.services.backend_torrent.loadBalancer]
    [[http.services.backend_torrent.loadBalancer.servers]]
      url = "http://172-104-239-86.ip.linodeusercontent.com:8081"
  [http.services.backend_filebrowser.loadBalancer]
    [[http.services.backend_filebrowser.loadBalancer.servers]]
      url = "http://172-104-239-86.ip.linodeusercontent.com:8024"

[http.middlewares.torrent-stripprefix.stripPrefix]
    prefixes = ["/torrent"]
[http.middlewares.filebrowser-stripprefix.stripPrefix]
    prefixes = ["/filebrowser"]
