# WHOAMI
http:
  routers:
    jelly:
      rule: "Host(`j.ozaki.one`)"
      service: backend_jelly
      tls:
        certResolver: "production"
        domains:
          - main: "ozaki.one"
            sans:
              - "*.ozaki.one"
    jellyseerr:
      rule: "Host(`js.ozaki.one`)"
      service: backend_jellyseerr
      tls:
        certResolver: "production"
        domains:
          - main: "ozaki.one"
            sans:
              - "*.ozaki.one"
    radarr:
      rule: "Host(`radarr.ozaki.one`)"
      service: backend_radarr
      tls:
        certResolver: "production"
        domains:
          - main: "ozaki.one"
            sans:
              - "*.ozaki.one"
    sonarr:
      rule: "Host(`sonarr.ozaki.one`)"
      service: backend_sonarr
      tls:
        certResolver: "production"
        domains:
          - main: "ozaki.one"
            sans:
              - "*.ozaki.one"
    prowlarr:
      rule: "Host(`prowlarr.ozaki.one`)"
      service: backend_prowlarr
      tls:
        certResolver: "production"
        domains:
          - main: "ozaki.one"
            sans:
              - "*.ozaki.one"
    homer:
      rule: "Host(`h.ozaki.one`)"
      service: backend_homer
      tls:
        certResolver: "production"
        domains:
          - main: "ozaki.one"
            sans:
              - "*.ozaki.one"
    whoami:
      rule: "Host(`w.ozaki.one`)"
      service: backend_whoami
      tls:
        certResolver: "production"
        domains:
          - main: "ozaki.one"
            sans:
              - "*.ozaki.one"
    qbittorrent:
      rule: "Host(`q.ozaki.one`)"
      service: backend_qbittorrent
      tls:
        certResolver: "production"
        domains:
          - main: "ozaki.one"
            sans:
              - "*.ozaki.one"
    deluge:
      rule: "Host(`d.ozaki.one`)"
      service: backend_deluge
      tls:
        certResolver: "production"
        domains:
          - main: "ozaki.one"
            sans:
              - "*.ozaki.one"
    portainer:
      rule: "Host(`p.ozaki.one`)"
      service: backend_portainer
      tls:
        certResolver: "production"
        domains:
          - main: "ozaki.one"
            sans:
              - "*.ozaki.one"
  services:
    backend_whoami:
      loadBalancer:
        servers:
          - url: "http://whoami:80/"
    backend_qbittorrent:
      loadBalancer:
        servers:
          - url: "http://qbittorrent:8888"
    backend_homer:
      loadBalancer:
        servers:
          - url: "http://homer:8080"
    backend_jelly:
      loadBalancer:
        servers:
          - url: "http://jellyfin:8096"
    backend_jellyseerr:
      loadBalancer:
        servers:
          - url: "http://jellyseerr:5055"
    backend_radarr:
      loadBalancer:
        servers:
          - url: "http://radarr:7878"
    backend_sonarr:
      loadBalancer:
        servers:
          - url: "http://sonarr:8989"
    backend_prowlarr:
      loadBalancer:
        servers:
          - url: "http://prowlarr:9696"
    backend_portainer:
      loadBalancer:
        servers:
          - url: "http://portainer:9000"
    backend_deluge:
      loadBalancer:
        servers:
          - url: "http://deluge:8112"
