# WHOAMI
http:
  routers:
    whoami:
      rule: "Host(`w.ozaki.one`)"
      service: backend_whoami
      tls:
        certResolver: "production"
    qbittorrent:
      rule: "Host(`q.ozaki.one`)"
      service: backend_qbittorrent
      tls:
        certResolver: "production"
  services:
    backend_whoami:
      loadBalancer:
        servers:
        - url: "http://whoami:80/"
    backend_qbittorrent:
      loadBalancer:
        servers:
        - url: "http://qbittorrent:8888"
