http:
  routers:
    jelly:
      rule: "Host(`j.home.ozaki.one`)"
      service: backend_jelly
      tls:
        certResolver: "production"
        domains:
          - main: "home.ozaki.one"
            sans:
              - "*.home.ozaki.one"
    seerr:
      rule: "Host(`seerr.home.ozaki.one`)"
      service: backend_seerr
      tls:
        certResolver: "production"
        domains:
          - main: "home.ozaki.one"
            sans:
              - "*.home.ozaki.one"
    radarr:
      rule: "Host(`radarr.home.ozaki.one`)"
      service: backend_radarr
      tls:
        certResolver: "production"
        domains:
          - main: "home.ozaki.one"
            sans:
              - "*.home.ozaki.one"
    sonarr:
      rule: "Host(`sonarr.home.ozaki.one`)"
      service: backend_sonarr
      tls:
        certResolver: "production"
        domains:
          - main: "home.ozaki.one"
            sans:
              - "*.home.ozaki.one"
    prowlarr:
      rule: "Host(`prowlarr.home.ozaki.one`)"
      service: backend_prowlarr
      tls:
        certResolver: "production"
        domains:
          - main: "home.ozaki.one"
            sans:
              - "*.home.ozaki.one"
    bazarr:
      rule: "Host(`bazarr.home.ozaki.one`)"
      service: backend_bazarr
      tls:
        certResolver: "production"
        domains:
          - main: "home.ozaki.one"
            sans:
              - "*.home.ozaki.one"
    jackett:
      rule: "Host(`ja.home.ozaki.one`)"
      service: backend_jackett
      tls:
        certResolver: "production"
        domains:
          - main: "home.ozaki.one"
            sans:
              - "*.home.ozaki.one"
    homer:
      rule: "Host(`h.home.ozaki.one`)"
      service: backend_homer
      tls:
        certResolver: "production"
        domains:
          - main: "home.ozaki.one"
            sans:
              - "*.home.ozaki.one"
    whoami:
      rule: "Host(`w.home.ozaki.one`)"
      service: backend_whoami
      tls:
        certResolver: "production"
        domains:
          - main: "home.ozaki.one"
            sans:
              - "*.home.ozaki.one"
    whoami-secure:
      rule: "Host(`ws.home.ozaki.one`)"
      service: backend_whoami
      tls:
        certResolver: "production"
        domains:
          - main: "home.ozaki.one"
            sans:
              - "*.home.ozaki.one"
    qbittorrent:
      rule: "Host(`q.home.ozaki.one`)"
      service: backend_qbittorrent
      tls:
        certResolver: "production"
        domains:
          - main: "home.ozaki.one"
            sans:
              - "*.home.ozaki.one"
    deluge:
      rule: "Host(`d.home.ozaki.one`)"
      service: backend_deluge
      tls:
        certResolver: "production"
        domains:
          - main: "home.ozaki.one"
            sans:
              - "*.home.ozaki.one"
    dockhand:
      rule: "Host(`dh.home.ozaki.one`)"
      service: backend_dockhand
      tls:
        certResolver: "production"
        domains:
          - main: "home.ozaki.one"
            sans:
              - "*.home.ozaki.one"
    portainer:
      rule: "Host(`p.home.ozaki.one`)"
      service: backend_portainer
      tls:
        certResolver: "production"
        domains:
          - main: "home.ozaki.one"
            sans:
              - "*.home.ozaki.one"
    homarr:
      rule: "Host(`ha.home.ozaki.one`)"
      service: backend_homarr
      tls:
        certResolver: "production"
        domains:
          - main: "home.ozaki.one"
            sans:
              - "*.home.ozaki.one"
  services:
    backend_whoami:
      loadBalancer:
        servers:
          - url: "http://whoami:80/"
    backend_qbittorrent:
      loadBalancer:
        servers:
          - url: "http://qbittorrent:8888"
    backend_homer:
      loadBalancer:
        servers:
          - url: "http://homer:8080"
    backend_jelly:
      loadBalancer:
        servers:
          - url: "http://jellyfin:8096"
    backend_seerr:
      loadBalancer:
        servers:
          - url: "http://seerr:5055"
    backend_radarr:
      loadBalancer:
        servers:
          - url: "http://radarr:7878"
    backend_sonarr:
      loadBalancer:
        servers:
          - url: "http://sonarr:8989"
    backend_prowlarr:
      loadBalancer:
        servers:
          - url: "http://prowlarr:9696"
    backend_portainer:
      loadBalancer:
        servers:
          - url: "http://portainer:9000"
    backend_deluge:
      loadBalancer:
        servers:
          - url: "http://deluge:8112"
    backend_dockhand:
      loadBalancer:
        servers:
          - url: "http://dockhand:3000"
    backend_homarr:
      loadBalancer:
        servers:
          - url: "http://homarr:7575"
    backend_bazarr:
      loadBalancer:
        servers:
          - url: "http://bazarr:6767"
    backend_jackett:
      loadBalancer:
        servers:
          - url: "http://jackett:9117"
