# WHOAMI
http:
  routers:
    whoami:
      rule: "Host(`w.ozaki.one`)"
      service: backend_whoami
      tls:
        certResolver: "myresolver"
        domains:
          - main: "ozaki.one"
            sans:
              - "*.ozaki.one"
    qbittorrent:
      rule: "Host(`q.ozaki.one`)"
      service: backend_qbittorrent
      tls:
        certResolver: "myresolver"
        domains:
          - main: "ozaki.one"
            sans:
              - "*.ozaki.one"
  services:
    backend_whoami:
      loadBalancer:
        servers:
        - url: "http://whoami:80/"
    backend_qbittorrent:
      loadBalancer:
        servers:
        - url: "http://qbittorrent:8888"
