# WHOAMI
http:
  routers:
    jelly:
      rule: "Host(`j.ozaki.one`)"
      service: backend_jelly
      tls:
        certResolver: "production"
        domains:
          - main: "ozaki.one"
            sans:
              - "*.ozaki.one"
    homer:
      rule: "Host(`h.ozaki.one`)"
      service: backend_homer
      tls:
        certResolver: "production"
        domains:
          - main: "ozaki.one"
            sans:
              - "*.ozaki.one"
    whoami:
      rule: "Host(`w.ozaki.one`)"
      service: backend_whoami
      tls:
        certResolver: "production"
        domains:
          - main: "ozaki.one"
            sans:
              - "*.ozaki.one"
    qbittorrent:
      rule: "Host(`q.ozaki.one`)"
      service: backend_qbittorrent
      tls:
        certResolver: "production"
        domains:
          - main: "ozaki.one"
            sans:
              - "*.ozaki.one"
  services:
    backend_whoami:
      loadBalancer:
        servers:
        - url: "http://whoami:80/"
    backend_qbittorrent:
      loadBalancer:
        servers:
        - url: "http://qbittorrent:8888"
    backend_homer:
      loadBalancer:
        servers:
        - url: "http://homer:8080"
    backend_jelly:
      loadBalancer:
        servers:
        - url: "http://jellyfin:8096"
