name: minecraftbedrock
services:
  mcbedrock:
    image: itzg/minecraft-bedrock-server
    volumes:
      - ./mcdata/:/data
    environment:
      EULA: "true"
      VERSION: latest
      DIFFICULTY: normal
    ports:
      - '19132:19132'
      - '19132:19132/udp'
