name: rustdesk

services:

  hbbr:
    image: rustdesk/rustdesk-server:latest
    container_name: hbbr
    volumes:
      - ./data:/root
    ports:
      - '21117:21117'
      - '21119:21119'
    networks:
      - rustdesk-net
    command: hbbr
    restart: unless-stopped
  hbbs:
    image: rustdesk/rustdesk-server:latest
    container_name: hbbs
    depends_on:
      - hbbr
    volumes:
      - ./data:/root
    ports:
      - '21115:21115'
      - '21116:21116'
      - '21116:21116/udp'
      - '21118:21118'
    networks:
      - rustdesk-net
    command: hbbs -r 192.168.1.13:21117
    restart: unless-stopped
networks:
  rustdesk-net:
    external: false
