version: "3.9"

services:
  homer:
    image: b4bz/homer
    container_name: homer
    restart: always
    # ports:
    #   - 8084:8080
    volumes:
      - ./assets:/www/assets
    environment:
      - INIT_ASSETS=0
    networks:
      - traefik

networks:
  traefik:
    name: traefik
    external: true
