version: "3"

services:
  adguard:
    image: adguard/adguardhome:latest
    container_name: adguard 
    ports:
      # - '53:53/tcp'
      # - '53:53/udp'
      # - '67:67/udp'
      # - '853:853/tcp'
      - '8085:80'
    volumes:
      - ./data/work:/opt/adguardhome/work
      - ./data/conf:/opt/adguardhome/conf
    restart: always

networks:
  traefik:
    name: traefik
    driver: bridge
    external: true
