version: "3"

services:
  adguard:
    image: adguard/adguardhome:latest
    container_name: adguard 
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '67:67/udp'
      - '853:853/tcp'
      - '8081:80/tcp'
    volumes:
      - ./adguard/work:/opt/adguardhome/work
      - ./adguard/conf:/opt/adguardhome/conf
    restart: always