---
name: deluge
services:
  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    volumes:
      - ./config/config:/config
      - ../jellyfin/data/torrent/downloads:/data/downloads
      - ../jellyfin/data/torrent/torrents:/data/torrents
      - ../jellyfin/data:/data
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Paris
      - DELUGE_LOGLEVEL=error #optional

    ports:
      - '6881:6881'
      - '6881:6881/udp'
      - '8112:8112'
      - '58846:58846' #optional
    networks:
      - traefik
    restart: unless-stopped

networks:
  traefik:
    name: traefik
    external: true
