name: jellyfin
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    volumes:
      - ./config:/config
      - ./data/media/tvshows:/data/tvshows
      - ./data/media/movies:/data/movies
      - ./data/media/music:/data/music
      - ./data/media/books:/data/books
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    ports:
      - '1900:1900/udp' #optional
      - '7359:7359/udp' #optional
      - '8096:8096'
      - '8920:8920' #optional
    networks:
      - traefik
    restart: unless-stopped

networks:
  traefik:
    name: traefik
    external: true
