version: "3.9"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./config:/config
      - ./data/media/tvshows:/data/tvshows
      - ./data/media/movies:/data/movies
      - ./data/media/music:/data/music
      - ./data/media/books:/data/books
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
    networks:
      - traefik

networks:
  traefik:
    name: traefik
    external: true
