name: ddclient
services:
  ddclient:
    image: ghcr.io/linuxserver/ddclient
    container_name: ddclient
    volumes:
      - ./data/config/:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    restart: unless-stopped
